apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.128.39.181/23"],"mac_address":"0a:58:0a:80:27:b5","gateway_ips":["10.128.38.1"],"routes":[{"dest":"10.128.0.0/16","nextHop":"10.128.38.1"},{"dest":"172.30.0.0/16","nextHop":"10.128.38.1"},{"dest":"100.64.0.0/16","nextHop":"10.128.38.1"}],"ip_address":"10.128.39.181/23","gateway_ip":"10.128.38.1"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.128.39.181"
          ],
          "mac": "0a:58:0a:80:27:b5",
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for container
      contenedor1; cpu, memory limit for container contenedor1'
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2024-07-03T09:27:58Z"
  name: pod-ivan
  namespace: ivancinigt-dev
  resourceVersion: "2440424369"
  uid: 062f8134-d964-41d6-9a3a-27e51549fcf1
spec:
  containers:
  - image: bitnami/nginx
    imagePullPolicy: Always
    name: contenedor1
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 10m
        memory: 64Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1012680000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-vdb9d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: default-dockercfg-fzhm5
  nodeName: ip-10-0-179-83.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: -3
  priorityClassName: sandbox-users-pods
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1012680000
    seLinuxOptions:
      level: s0:c113,c12
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: kube-api-access-vdb9d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-07-03T09:27:58Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-07-03T09:28:03Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-07-03T09:28:03Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-07-03T09:27:58Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://6051e1792fd19d091df8187a62fca49235df1a24e020ee74d2c4d4336e08135a
    image: docker.io/bitnami/nginx:latest
    imageID: docker.io/bitnami/nginx@sha256:0f6c0a48e874645b7c2732ebc5f196787318050de9334e03a457813fd80115cf
    lastState: {}
    name: contenedor1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-07-03T09:28:03Z"
  hostIP: 10.0.179.83
  phase: Running
  podIP: 10.128.39.181
  podIPs:
  - ip: 10.128.39.181
  qosClass: Burstable
  startTime: "2024-07-03T09:27:58Z"
